src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    use TimestampableEntity;

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private ?int $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private ?string $email;

    /**
     * @ORM\Column(type="json")
     */
    private array $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private string $password;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private ?\DateTimeInterface $lastPasswordChange;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private ?string $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private ?string $lastName;

    /**
     * @ORM\Column(type="date")
     */
    private ?\DateTimeInterface $birthDate;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getLastPasswordChange(): ?\DateTimeInterface
    {
        return $this->lastPasswordChange;
    }

    public function setLastPasswordChange(?\DateTimeInterface $lastPasswordChange): self
    {
        $this->lastPasswordChange = $lastPasswordChange;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getBirthDate(): ?\DateTimeInterface
    {
        return $this->birthDate;
    }

    public function setBirthDate(\DateTimeInterface $birthDate): self
    {
        $this->birthDate = $birthDate;

        return $this;
    }

    public function updatePassword(string $password): self
    {
        $this->password = $password;
        $this->lastPasswordChange=new \DateTime();
        return $this;
    }
}

src/Controller/DefaultController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Message\NewAccountMessage;
use App\Repository\UserRepository;
use Doctrine\Persistence\ManagerRegistry;
use Knp\Component\Pager\PaginatorInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use SimpleXLS;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Messenger\MessageBusInterface;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Annotation\Route;
use App\Form\ImportUsersType;

/**
 * @IsGranted("ROLE_USER")
 */
class DefaultController extends AbstractController
{

    private ManagerRegistry $managerRegistry;
    private MessageBusInterface $messageBus;

    public function __construct(ManagerRegistry $managerRegistry,MessageBusInterface $messageBus)
    {
        $this->managerRegistry = $managerRegistry;
        $this->messageBus = $messageBus;
    }
    /**
     * @Route("/", name="app_home")
     */
    public function index(): Response
    {
        return $this->render('default/index.html.twig', [
            'controller_name' => 'DefaultController',
        ]);
    }


    /**
     * @Route("/users/{page}", name="app_users_list", requirements={"page":"\d+"}, defaults={"page":1})
     * @param UserRepository $repository
     * @param PaginatorInterface $paginator
     * @param int $page
     * @return Response
     */
    public function usersList(UserRepository $repository,PaginatorInterface $paginator,int $page): Response
    {
        /** @var User $user */
        $user=$this->getUser();
        return $this->render('default/users.html.twig', [
            'pagination' => $paginator->paginate(
                $repository->findAllOthers($user),$page,$this->getParameter('items_per_page'),[]),
            'manage'=>false
        ]);
    }

    /**
     * @Route("/import_users", name="app_import_users")
     * @param Request $request
     * @param UserPasswordHasherInterface $passwordEncoder
     * @return Response
     */
    public function importUsersAction(Request $request,UserPasswordHasherInterface $passwordEncoder): Response
    {
        $form=$this->createForm(ImportUsersType::class);
        $form->handleRequest($request);

        if($form->isSubmitted()&&$form->isValid())
        {
            $file=$form->getData()['file'];
            try{
                $stats=$this->parseFile($file,$passwordEncoder);
            }catch(\Throwable $ex)
            {
                $error = $ex->getMessage();
            }

        }

        return $this->render('default/import.html.twig',[
            'form' => $form->createView(),
            'stats'=> $stats ?? null,
            'error'=> $error ?? null
        ]);
    }

    private function parseFile($file,UserPasswordHasherInterface $passwordEncoder): array
    {
        $xls=SimpleXLS::parse($file);
        $em=$this->managerRegistry->getManager();
        $repository=$this->managerRegistry->getRepository('App:User');
        $stats=array('new'=>array(),'error'=>array());
        foreach ($xls->rows() as $num=> $row)
        {
            list($valid,$error)=$this->validRow($row,$repository);
            if($valid)
            {
                $user=new User();
                $user
                    ->setFirstName($row[0])
                    ->setLastName($row[1])
                    ->setEmail($row[2])
                    ->setBirthDate(new \DateTime($row[3]))
                ;
                $password=$this->generatePassword();
                $user->setPassword($passwordEncoder->hashPassword($user,$password));
                $em->persist($user);
                $this->messageBus->dispatch(
                    new NewAccountMessage(
                        $user->getEmail(),
                        $password
                    )
                );
                $stats['new'][]=$user;
            }else{
                $stats['error'][$num+1]=$error;
            }
            $em->flush();

        }
        return $stats;
    }

    /**
     * @param $row
     * @param UserRepository $repository
     * @return array
     */
    private function validRow($row, UserRepository $repository): array
    {
        $valid=true;
        $error=null;
        if(
            gettype($row[0])=='string'&&
            gettype($row[1])=='string'&&
            filter_var($row[2], FILTER_VALIDATE_EMAIL)&&
            $this->checkDate($row[3])
        ){
            $exist=$repository->findOneBy(['email'=>$row[2]]);
            if(!is_null($exist))
            {
                $valid=false;
                $error='User_exists';
            }
        }else{
            $valid=false;
            $error='Invalid_data';
        }
        return array(
            $valid,
            $error
        );
    }

    private function checkDate($date): bool
    {
        try {
            $date = new \DateTime($date);
            return true;
        } catch (\Exception $e) {
            return false;
        }
    }

    private function generatePassword(): string
    {
        $alphabet = "abcdefghijklmnopqrstuwxyzABCDEFGHIJKLMNOPQRSTUWXYZ0123456789_-";
        $pass = array();
        $alphaLength = strlen($alphabet) - 1;
        for ($i = 0; $i < 10; $i++) {
            $n = rand(0, $alphaLength);
            $pass[] = $alphabet[$n];
        }
        return implode($pass);
    }
}

templates/default/header.html.twig
<header class="bg-dark">
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-dark">
            <div class="collapse navbar-collapse flex-grow-1 text-right" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto flex-nowrap">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {% if app.user %}
                            {% trans %}logged.as{% endtrans %}: {{ app.user.userIdentifier }}
                            {% else %}
                                {% trans %}guest{% endtrans %}
                            {% endif %}
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            {% if app.user %}

                                <a class="dropdown-item" href="{{ path('app_profile')}}">{% trans %}profile.my{% endtrans %}</a>
                                <a class="dropdown-item" href="{{ path('app_users_list')}}">{% trans %}profile.others{% endtrans %}</a>
                                <a class="dropdown-item" href="{{ path('app_change_password')}}">{% trans %}profile.change_password.text{% endtrans %}</a>
                                <a class="dropdown-item" href="{{path('app_logout')}}">{% trans %}logout{% endtrans %}</a>
                            {% else %}
                                <a class="dropdown-item" href="{{ path('app_login')}}">{% trans %}login{% endtrans %}</a>
                            {% endif %}

                        </div>
                    </li>
                </ul>
            </div>
        </nav>
    </div>
</header>

templates/default/import.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% trans %}Importuj użytkowników{% endtrans %}{% endblock %}

{% block body %}
<div>
    <h3>{% trans %}Import użytkowników{% endtrans %}</h3>
    {{ form_start(form) }}
        <div class="form-group row">
            <div class="col-12 col-sm-3 col-form-label">
                {{form_label(form.file)}}
            </div>
            <div class="col-12 col-sm-9">
                {{ form_widget(form.file) }}
            </div>
        </div>
    {{ form_widget(form.submit) }}
    {{ form_end(form) }}
    {% if stats is not null %}
        <p class="text-success">Zaimportowano {{ stats.new|length }}nowych użytkowników</p>
        {% if stats.error|length >0 %}
            {% for num,error in stats.error %}
                <p class="text-danger">Wiersz {{ num }}: {{ error|importError }}</p>
            {% endfor %}
            {% endif %}
    {% endif %}
    <div class="alert alert-info mt-2">
        <p class="font-weight-bold">{% trans %}import.columns_order{% endtrans %}:</p>
        <ul>
            <li>{% trans %}firstName{% endtrans %}</li>
            <li>{% trans %}lastName{% endtrans %}</li>
            <li>{% trans %}email{% endtrans %}</li>
            <li>{% trans %}birthDate{% endtrans %}</li>
        </ul>
    </div>
</div>
{% endblock %}

templates/default/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Strona główna{% endblock %}

{% block body %}

    <div class="btn-group btn-group-sm">
    <a href="{{ path('app_import_users') }}" class="btn btn-primary">Importuj użytkowników</a>
    <a href="{{ path('app_users_list') }}" class="btn btn-secondary">Lista użytkowników</a>
    </div>
{% endblock %}

templates/default/users.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% trans %}Lista użytkowników{% endtrans %}{% endblock %}

{% block body %}


    <div class="table-responsive">
        <table id="usersTable" class="table table-striped">
            <thead>
                <tr>
                    <th>{% trans %}Id{% endtrans %}</th>
                    <th>{% trans %}firstName{% endtrans %}</th>
                    <th>{% trans %}lastName{% endtrans %}</th>
                    <th>{% trans %}email{% endtrans %}</th>
                    <th>{% trans %}birthDate{% endtrans %}</th>
                    <th>{% trans %}regDate{% endtrans %}</th>
                </tr>
            </thead>
            <tbody>
                {% for user in pagination %}
                    <tr>
                        <td>{{ user.id }}</td>
                        <td>{{ user.firstName }}</td>
                        <td>{{ user.lastName }}</td>
                        <td>{{ user.email }}</td>
                        <td>{{ user.birthDate|date('d/m/Y') }}</td>
                        <td>{{ user.createdAt|date('d/m/Y H:i:s') }}</td>
                    </tr>
                    {% else %}
                    <tr>
                        <td colspan="6">{% trans %}Pusto{% endtrans %}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <div class="navigation">
        {{ knp_pagination_render(pagination) }}
    </div>
{% endblock %}